spring.application.name=tournament-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/tournament_management_system
spring.datasource.username=postgres
spring.datasource.password=hammad123